In [6]:
import torch

data1 = torch.tensor([[1,2,3], [4,5,6]])
print(data1)
# Convert tensor data into python list data form
data1_1 = data1.data.tolist()
print(data1_1)

tensor([[1, 2, 3],
        [4, 5, 6]])
[[1, 2, 3], [4, 5, 6]]


In [8]:
data2 = torch.randn(8)
print(data2)

data1_ones = torch.ones_like(data1)
data1_zeros = torch.zeros_like(data1)
print(data1_ones)
print(data1_zeros)

tensor([-0.2608, -1.8372,  0.1311, -2.0196,  1.2115,  0.5272, -2.1727,  1.9697])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0]])
