In [1]:
import torch

##################################################################################
# transpote & permute examples
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

print(a.shape, a_t.shape)
print(a)
print(a_t)


torch.Size([3, 2]) torch.Size([2, 3])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [9]:
b = torch.ones(2, 4)
b_t = b.transpose(0, 1)
print(b.shape, b_t.shape)
print(b)
print(b_t)

torch.Size([2, 4]) torch.Size([4, 2])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [16]:
##################################################################################
# storage  (indexing into storage)
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)
print(points.storage())
print(points.untyped_storage())

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
 0
 0
 128
 64
 0
 0
 128
 63
 0
 0
 160
 64
 0
 0
 64
 64
 0
 0
 0
 64
 0
 0
 128
 63
[torch.storage.UntypedStorage(device=cpu) of size 24]


In [19]:
points_storage = points.storage()
print('points_storage = ', points_storage[0])
print('points.storage()[1] = ', points.storage()[1])

points_storage =  4.0
points.storage()[1] =  1.0
