In [ ]:
class CustomNumbers:
  def __init__(self, num):
    self.numbers1 = [n for n in range(1, num)]
    self.numbers2 = [n * 2 for n in range(1, num)]

  def __getitem__(self, idx):
    return self.numbers1[idx]

  def __len__(self):
    return len(self.numbers1)

In [ ]:
obj = CustomNumbers(11)
print(obj.numbers1[2:5])
print(obj[2:5])

[3, 4, 5]
[3, 4, 5]


In [ ]:
obj = CustomNumbers(101)
print(len(obj))

100


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

In [ ]:
class MyDataset(Dataset):
    def __init__(self, x_data, y_data):
        self.x_data = x_data
        self.y_data = y_data

    def __getitem__(self, idx):
        return self.x_data[idx], self.y_data[idx]

    def __len__(self):
        return len(self.x_data)

In [ ]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152],
                             [185],
                             [180],
                             [196],
                             [142]])
dataset = MyDataset(x_train, y_train)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [ ]:
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
nb_epochs = 20
for epoch in range(nb_epochs+1):
  for batch_idx, samples in enumerate(dataloader):
    x_train, y_train = samples
    print(x_train, y_train, sep='\n')
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {}/{} Cost: {}'.format(epoch, nb_epochs, cost.item()))

tensor([[ 93.,  88.,  93.],
        [ 96.,  98., 100.]])
tensor([[185.],
        [196.]])
Epoch 0/20 Cost: 49901.2109375
tensor([[73., 66., 70.],
        [73., 80., 75.]])
tensor([[142.],
        [152.]])
Epoch 0/20 Cost: 6267.80908203125
tensor([[89., 91., 90.]])
tensor([[180.]])
Epoch 0/20 Cost: 4253.23046875
tensor([[ 96.,  98., 100.],
        [ 93.,  88.,  93.]])
tensor([[196.],
        [185.]])
Epoch 1/20 Cost: 1365.044677734375
tensor([[73., 66., 70.],
        [73., 80., 75.]])
tensor([[142.],
        [152.]])
Epoch 1/20 Cost: 169.26812744140625
tensor([[89., 91., 90.]])
tensor([[180.]])
Epoch 1/20 Cost: 90.90290832519531
tensor([[93., 88., 93.],
        [73., 66., 70.]])
tensor([[185.],
        [142.]])
Epoch 2/20 Cost: 49.06129455566406
tensor([[ 73.,  80.,  75.],
        [ 96.,  98., 100.]])
tensor([[152.],
        [196.]])
Epoch 2/20 Cost: 4.499648094177246
tensor([[89., 91., 90.]])
tensor([[180.]])
Epoch 2/20 Cost: 0.7126352190971375
tensor([[73., 80., 75.],
        [93., 88

In [ ]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print('훈련 후 입력이 73, 80, 75 일 때의 예측값: ', pred_y.item())

훈련 후 입력이 73, 80, 75 일 때의 예측값:  153.69271850585938
