In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader

In [2]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152],
                             [185],
                             [180],
                             [196],
                             [142]])
dataset = TensorDataset(x_train, y_train)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [3]:
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [4]:
nb_epochs = 20
for epoch in range(nb_epochs+1):
  for batch_idx, samples in enumerate(dataloader):
    x_train, y_train = samples
    print(x_train, y_train, sep='\n')
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {}/{} Cost: {}'.format(epoch, nb_epochs, cost.item()))

tensor([[ 96.,  98., 100.],
        [ 89.,  91.,  90.]])
tensor([[196.],
        [180.]])
Epoch 0/20 Cost: 68963.328125
tensor([[93., 88., 93.],
        [73., 80., 75.]])
tensor([[185.],
        [152.]])
Epoch 0/20 Cost: 12435.0283203125
tensor([[73., 66., 70.]])
tensor([[142.]])
Epoch 0/20 Cost: 3078.184814453125
tensor([[ 93.,  88.,  93.],
        [ 96.,  98., 100.]])
tensor([[185.],
        [196.]])
Epoch 1/20 Cost: 2477.6416015625
tensor([[89., 91., 90.],
        [73., 66., 70.]])
tensor([[180.],
        [142.]])
Epoch 1/20 Cost: 418.17242431640625
tensor([[73., 80., 75.]])
tensor([[152.]])
Epoch 1/20 Cost: 111.6463623046875
tensor([[73., 80., 75.],
        [93., 88., 93.]])
tensor([[152.],
        [185.]])
Epoch 2/20 Cost: 76.8507308959961
tensor([[ 96.,  98., 100.],
        [ 89.,  91.,  90.]])
tensor([[196.],
        [180.]])
Epoch 2/20 Cost: 15.137161254882812
tensor([[73., 66., 70.]])
tensor([[142.]])
Epoch 2/20 Cost: 23.00473976135254
tensor([[ 96.,  98., 100.],
        [ 73.

In [ ]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print('훈련 후 입력이 73, 80, 75 일 때의 예측값: ', pred_y.item())

훈련 후 입력이 73, 80, 75 일 때의 예측값:  154.84690856933594
